version: "2"
services:
    frontend:
      container_name: frontend
      build:
          context: .
          dockerfile: Dockerfile
      ports:
          - "3000:3000"
    backend:
      container_name: backend
      restart: always
      build:
          context: ./server
          dockerfile: Dockerfile
      ports:
          - "3001:3001"
      depends_on:
        - mongo
    mongo:
      container_name: mongo
      image: mongo
      ports:
        - "27017:27017"